name: build music.prx

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PSPTOOLCHAIN
        uses: krystalgamer/setup-psptoolchain@latest

      - name: build music.prx
        run: cd music1 ; make

      - name: build music2.prx
        run: cd music2 ; make

      - name: Release package
        uses: softprops/action-gh-release@master
        with:
          name: music
          tag_name:  music
          body: |
            music psp plugin for CFW
          files: |
            music1/music.prx
            music2/*.prx
          token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_unmatched_files: true
