name: build mp3play

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PSPTOOLCHAIN
        uses: krystalgamer/setup-psptoolchain@latest

      - name: build mp3play
        run: make

      - name: Release package
        uses: softprops/action-gh-release@master
        with:
          name: mp3play
          tag_name:  mp3play
          body: |
            mp3play psp plugin for CFW
          files: |
            mp3play.prx
          token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_unmatched_files: true
